# Copyright (c) 2023-2024, NVIDIA CORPORATION.
name: cudf-pandas-integration test on default branch (nightly / manually)

on:
  workflow_dispatch:
    # The below exists in alignment with rest of RAPIDS nightly pipeline. They are currently unused.
    inputs:
      branch:
        required: true
        type: string
      date:
        required: true
        type: string
      sha:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract libraries from dependencies.yaml
        id: extractlib
        run: |
          LIBS=$(python/cudf/cudf_pandas_tests/third_party_integration_tests/ci/extract_lib.sh python/cudf/cudf_pandas_tests/third_party_integration_tests/dependencies.yaml)
          echo "LIBS=${LIBS}" >> $GITHUB_ENV

      - name: Run integration tests
        run: |
          for lib in ${{ env.LIBS }}; do
            echo "Running tests for $lib"
            CUDA_MAJOR=$(if [ "$lib" = "tensorflow" ]; then echo "11"; else echo "12"; fi)
            python/cudf/cudf_pandas_tests/third_party_integration_tests/ci/test.sh $lib $CUDA_MAJOR
          done
        env:
          LIBS: ${{ env.LIBS }}
    secrets: inherit
